#### This is Anna Horton's sixth GEOG 592 Homework on NumPy and arrays. 
Name: Anna Horton
ONYEN: arhorton
Date: 09/23/2026

In [77]:
# code for section one
locations = ["Oak", "Pine", "Maple", "Cedar", "Elm"]

locations[0]
locations[1:4]

['Pine', 'Maple', 'Cedar']

##### Python indexing refresher questions

1) 'Oak' is returned.
2) 'Elm' is returned.
3) The values that are returned by locations[1:4] are the values that correspond to indexes 1:3, which are ["Pine", "Maple", "Cedar"].
4) locations[2] returns 'Maple'.

In [78]:
# code for section two
points = [[100, 200], [140, 230], [180, 260], [120, 280]]

print(points[2][1])
print(points[1][0])

260
140


##### Python indexing refesher questions part 2

5) It returns [180, 260], or the values at the second index or row three.
6) points[2][1] returns the second value in the third row of the dataframe. The first index selects the row number (given that the index values start at zero, this is the third row), and the second index selects the value's index within that row. 
7) points[1][0] will return the x-coordinate of the second point. 

In [79]:
# code for section three
import pandas as pd 

df = pd.DataFrame({
"name": ["Oak", "Pine", "Maple", "Cedar"],
"ft": [25, 48, 31, 60],
"zone": ["A", "B", "A", "B"]
})

print(df.iloc[0:3])
print(df[df["ft"] > 30])
print(df.iloc[1:3])

    name  ft zone
0    Oak  25    A
1   Pine  48    B
2  Maple  31    A
    name  ft zone
1   Pine  48    B
2  Maple  31    A
3  Cedar  60    B
    name  ft zone
1   Pine  48    B
2  Maple  31    A


##### Pandas indexing refresher questions

8) A Pandas Series object is returned. 
9) df[["name", "ft"]] selects both the name and the feet columns at the same time. 
10) The second row is returned by df.iloc(1).
11) The first three rows are selected by typing in: df.iloc[0:3].
12) Rows where feet is greater than 30 can be referenced with df = df[["ft] > 30]. 
13) The rows that are returned by df.iloc[1:3] are the rows labeled "ft" and "zone", as they are within the index boundaries and correspond to specific rows. 

In [80]:
# code for section 4
import numpy as np
points = np.array([
[100, 200],
[140, 230],
[180, 260],
[120, 280]
])

print(points[0])
print(points[0,1])
print(points[:, 0])
print(points[:, 1])
print(points[1:3])
print("This is the second value in the third row:",  points[2][1])
print("This is the second value in the third row:", points[2, 1])

[100 200]
200
[100 140 180 120]
[200 230 260 280]
[[140 230]
 [180 260]]
This is the second value in the third row: 260
This is the second value in the third row: 260


##### Moving to NumPy arrays questions

14) Points.shape returns (4, 2), which indicates that there are four rows and 2 columns within the array.
15) Points[0] returns [100, 200].
16) Points[0, 1] returns 200. The colon between the numbers does not mean multiple rows, it means only the row and column indexes. 
17) The colon indicates that all of the rows are selected and the second index is referencing only the column numbers. It would return all of the values within the second column, which in this case is the x value of the points. 
18) This is a similar problem, except this time, the y values are returned. 
19) points[1:23] will pull out the second and third rows. 
20) The points[2][1] returns the second value in the third row of the array; points[2, 1] returns the 2nd value in the third row. They return the same value but are different manners in which to return it. 

In [81]:
# code for section five
shift = np.array([10, 20])

##### Vectorized operations questions

21) The original points detailed in the points array created above will all return as slightly modified according to the shift array created above. The x values will all be shifted by 10 and the y values by 20.
22) There is no need to introduce a Python for loop into the equation because the for loop is much slower than the vectorized operation which the array can execute. It can apply a condition to each of the values within an array almost instataneously.  

In [82]:
# code for section six
x = points[:, 0]
y = points[:, 1]
inside = (x >= 110) & (x <= 150) & (y >= 220) & (y <= 290)

print(inside[:])
print(points[inside])

[False  True False  True]
[[140 230]
 [120 280]]


##### Boolean masks and spatial queries questions

23) inside[:] will return a Boolean of the status of that row. If both values in the row do not fit the condition, it will not be returned. In this case, the pattern is: False True False True. 
24) points[inside] returns a smaller modified dataframe that returns only the points that fit the mask specifically. In this case, it means that the x value is between 110 and 150 and the y value is between 220 and 290. If only one half of the value pair fits, it is excluded. 
25) In GIS language, the spatial operation is an intersect. We are asking where one layer lands on top of the other and how we might be able to use those results for additional analysis. 

In [83]:
# code for section 7
elevation = np.array([240, 510, 430, 680])
classes = np.where(elevation >= 500, 1, 0)

##### np.where() and classification questions

26) The values that are stored in classes refer to the values that were assigned to the previous array if the values at that index met a condition. In this case, the 1 is acting as a yes, the condition is true, and the 0 is acting as a no, it is false. The values returned will be [510, 680].
27) In np.where(), there are three parameters. The first parameter refers to the condition that you want the values to be compared against. The second parameter is what you would like to assign the values that fit the condition, and the third parameter is the same as the second except for it is assigned if the condition is not met. 

In [84]:
# code for section 8
a = np.array([100, 200])
b = np.array([140, 230])
distance = np.sqrt(((a - b) ** 2).sum())

print(a - b)

[-40 -30]


##### Distance and pandas connection questions

28) a - b returns [- 40, - 30].
29) The distance calculation is an example of vectorized arithmetic because it applies to each value in the array almost instantaneously when the function is called/ 

In [85]:
# code for section 8 part 2
ft_array = df["ft"].to_numpy()

print(ft_array)
print(ft_array[0])

[25 48 31 60]
25


##### Distance and pandas connection questions part 2

30) Before its converstion to a NumPy array, ft_array was a pandas Series.
31) When the Series was converted to an array, the pandas index remains the same and the column labels disappear. 

##### Final questions!

32) locations[2] for a Python list selects the third row. 
points_list[2][1] for a nested python list selects the third list and the second value in that list.
df.iloc[2, 1] selects the third row and the second value. 
points[2, 1] in a NumPy array selects the third row, second value (similar to above).
points[:, 0] selects all of the zeroth (or first) column in the array. 
33) The recurring index idea that persists across each of the three types of Python data is that the index always starts at zero, so slicing always works the same. Additionally, the row is always written first and the column second. 
34) It is much easier to apply calculations when the data is in the form of a NumPy array: no loops are needed and there is vectorized computation. 

##### I struggled with questions 3, 11, 12, 13, 16, 17, 19, 23, 24, 26, 28, and 31. I will ensure to study those before the assessment on Friday. 